# Generated by Django 3.1.3 on 2020-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Default value', max_length=50),
            preserve_default=False,
        ),
    ]
