# Generated by Django 3.1 on 1980-01-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_19800102_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter the date in this formatyyyy/mm/ddexample: 2000/01/01', null=True),
        ),
    ]
